### ISSUE TITLE
ISSUE CHECKLIST

### ISSUE THREAD

**Issue by gmdEzreal** [gmdEzreal/GMDeck#2]
- [ ] The latest commit at the time of discovering the bug
- [ ] Describes the bug
- [ ] How to reproduce the bug
